---
title: "02_prism_data"
author: "Puvvula"
date: "2023-12-05"
output: pdf_document
---

```{r}
library(pacman)
p_load(sf, prism, raster)
```

```{r}
x<- raster("/Volumes/One Touch/PRISM_data/an/tmax/daily/2008/prism_tmax_us_30s_20080101.bil")

plot(x)
```

```{r}
result <- getRasterValue(42.54090	, -71.13385, 
                         "/Volumes/One Touch/PRISM_data/an/tmax/daily/2018/prism_tmax_us_30s_20180402.bil")
```


```{r}
start_date <- as.Date("2018-03-27")  # Replace with your start date
end_date <- as.Date("2018-04-02")    # Replace with your end date
partial_folder <- "/Volumes/One Touch/PRISM_data/an/tmax/daily"  # Replace with your partial folder name

result <- getRasterValueInRange(42.54090, -71.13385, 
                                partial_folder, 
                                start_date, 
                                end_date)

print(result)
```

# attempt automation
```{r}
sim_df <- data.frame(
  latitude = runif(20, 40.5, 45.0),
  longitude = runif(20, -75.0, -70.0),
  lmp_date = as.Date("2019-01-01") - sample(34:40, 20, replace = TRUE) * 7,
  delivery_date = as.Date("2019-01-01") - sample(34:40, 20, replace = TRUE) * 7
)
```

```{r}
x_df<-getRasterValueInRange(dataframe = sim_df,
                      partial_folder_name = "/Volumes/One Touch/PRISM_data/an/tmax/daily")
```


